widget_group3/forum/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('forumposts/add/', PostCreateView.as_view(), name='addPost'),
    path('forumposts/<int:pk>/details', PostDetailView.as_view(), name='PostDetailView'),
    path('forumposts/<int:pk>/edit', PostUpdateView.as_view(), name='PostUpdateView'),
]

app_name="forum"

widget_group3/widget_group3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('calendar/', include('calendar_app.urls', namespace="calendar_app")),
    path('forum/', include('forum.urls', namespace="forum")),
    path('assignments/', include('Assignments.urls', namespace="Assignments")),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('announcements/', include('announcements.urls', namespace="announcements")),
]

widget_group3/forum/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class ForumPost (models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    author = models.ForeignKey('dashboard.WidgetUser', on_delete=models.CASCADE, null=True)
    pub_datetime = models.DateTimeField(auto_now_add=True)
   
    
    def __str__(self):
        return self.title
        
    def datetime_posted(self):
        return self.pub_datetime.strftime('%m/%d/%Y, %I:%M %p')
        
    def get_absolute_url(self):
        return reverse('forum:PostDetailView', kwargs={'pk': self.pk})
        
    def get_update_url(self):
        return reverse('forum:PostUpdateView', kwargs={'pk': self.pk})
        
        
class Reply (models.Model):
    body = models.TextField()
    author = models.ForeignKey('dashboard.WidgetUser', on_delete=models.CASCADE, null=True)
    pub_datetime = models.DateTimeField(auto_now_add=True)
    forum_post = models.ForeignKey(ForumPost, on_delete=models.CASCADE, related_name = 'post_replies')
    
    def datetime_posted(self):
        return self.pub_datetime.strftime('%m/%d/%Y, %I:%M %p')
        
     

widget_group3/forum/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import ForumPost, Reply
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView

# Create your views here.
def index(request):
    post_list = reversed(ForumPost.objects.all())
    return render(request,"forum/forum.html",{"posts":post_list})
    
class PostCreateView(CreateView):
    model = ForumPost
    fields = '__all__'
    template_name = 'forum/forumpost-add.html'

class PostUpdateView(UpdateView):
    model = ForumPost
    fields = '__all__'
    template_name = 'forum/forumpost-edit.html'
    
class PostDetailView(DetailView):
    model = ForumPost
    template_name = 'forum/forumpost-details.html'
    


widget_group3/forum/templates/forum/forum.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Widget's Forum
{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}
<h1>Welcome to Widget's Forum</h1>
<h2>Forum posts:</h2>

<div>
{% for post in posts %}
<a href = "{{post.get_absolute_url}}">"{{post.title}}" by {{post.author.first_name}} {{post.author.last_name}}</a>
<br>
{% endfor %}
<br><br><br>
<a href = "{% url 'forum:addPost' %}"><button>New Post</button></a>
<br><br>
<a href="/dashboard">Dashboard</a>
<br>
<a href="/announcements">Announcements</a>
<br>
<a href="/assignments">Assignments</a>
<br>
<a href="/calendar">Calendar</a>
<br>

{% endblock %}

widget_group3/forum/templates/forum/forumpost-add.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}
<h1> Add a new post:</h1><br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %} 
    {{ form.as_p }}
    <input type="submit" value="Save New Post">
{% endblock %}

widget_group3/forum/templates/forum/forumpost-details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{object.title}}
{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}
<p1>
<h1>{{object.title}}</h1>
by {{object.author.first_name}}, {{object.author.last_name}} 
<br>
{{object.datetime_posted}}
<br>
{{object.body}}
</p1>
<br><br>
<p2>
Post Replies: <br><br>
{% for reply in object.post_replies.all %}
by {{reply.author.first_name}} {{reply.author.last_name}} <br>
{{reply.datetime_posted}} <br>
{{reply.body}} <br>
<br>
{% endfor %}
</p2>
<br>
<a href = "{{object.get_update_url}}"><button>Edit Post</button></a>
{% endblock %}

widget_group3/forum/templates/forum/forumpost-edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Edit Post
{% endblock %}

{% block styles %}
{% endblock %}

{% block content %}
<h1>Edit Post</h1><br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %} 
    {{ form.as_p }}
    <input type="submit" value="Save Changes to Post">
{% endblock %}