widget_group3/calendar_app/urls.py
#calendar_app/urls

from django.urls import path

from .views import event_view, EventDetailView, EventCreateView, EventUpdateView

urlpatterns = [
    path('', event_view, name='event_view'),
    path('events/<int:pk>/details/', EventDetailView.as_view(), name='event-details'),
    path('events/add', EventCreateView.as_view(), name='event-add'),
    path('events/<int:pk>/edit', EventUpdateView.as_view(), name='event-edit'),
]


app_name = "calendar_app"

widget_group3/forum/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('forumposts/add/', PostCreateView.as_view(), name='addPost'),
    path('forumposts/<int:pk>/details', PostDetailView.as_view(), name='PostDetailView'),
    path('forumposts/<int:pk>/edit', PostUpdateView.as_view(), name='PostUpdateView'),
]

app_name="forum"

widget_group3/widget_group3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('calendar/', include('calendar_app.urls', namespace="calendar_app")),
    path('forum/', include('forum.urls', namespace="forum")),
    path('assignments/', include('Assignments.urls', namespace="Assignments")),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('announcements/', include('announcements.urls', namespace="announcements")),
]

widget_group3/calendar_app/models.py
from django.db import models
from Assignments.models import Course 
from django.urls import reverse

class Event(models.Model):
    activity = models.CharField(max_length=100)
    target_datetime = models.DateTimeField()
    estimated_hours = models.FloatField()
    location = models.ForeignKey(
        'Location',
        on_delete = models.CASCADE,
    )   
    course = models.ForeignKey(
        'Assignments.Course',
        on_delete = models.CASCADE,
    )
    
    def __str__(self):
        return '{} on {}'.format(self.activity, self.target_datetime)

    
class Location(models.Model):
    mode_choices = [
        ('onsite','onsite'),
        ('online','online'),
        ('hybrid','hybrid'),    
    ]
    mode = models.CharField(
        max_length=6,
        choices=mode_choices,
        default='onsite',        
    )
    venue = models.CharField(max_length=200)
    
    def __str__(self):
        return '{} - {}'.format(self.mode, self.venue)

widget_group3/calendar_app/views.py
#References: 
 # Queries - Django Documentation
 # https://docs.djangoproject.com/en/4.1/topics/db/queries/#retrieving-a-single-object-with-get

 # Datetime Import
 # https://docs.python.org/3/library/datetime.html

from django.shortcuts import render
from django.http import HttpResponse
from .models import Event, Location
from django.views.generic import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.urls import reverse
import datetime
 
def event_view(request):
    event = Event.objects.all()
    return render(request, 'calendar_app/calendar.html', {'event': event})

class EventDetailView(DetailView):
    model = Event
    template_name = 'calendar_app/event-details.html'

class EventCreateView(CreateView):
    model = Event
    fields = '__all__'
    template_name = 'calendar_app/event-add.html'
    
    #after creating form, sends user to detail page of created activity
    def get_success_url(self):
       return reverse('calendar_app:event-details', kwargs={'pk': self.object.pk})

class EventUpdateView(UpdateView):
    model = Event
    fields = '__all__'
    template_name = 'calendar_app/event-edit.html'
    
    #after updating form, sends user to detail page of created activity
    def get_success_url(self):
       return reverse('calendar_app:event-details', kwargs={'pk': self.object.pk})

widget_group3/calendar_app/templates/calendar_app/calendar.html
<!-- calendar html -->
{% extends 'base.html' %}
{% load static %}
{% block title %}Widget's Calendar of Activities{% endblock %}
{% block content %}
<h1>Widget's Calendar of Activities</h1>
{%for object in event%}
<a href="{% url 'calendar_app:event-details' object.id %}">{{ object.activity }}</a>
<br>
{%endfor%}
<br>

<a href="{% url 'calendar_app:event-add'%}"><button>New Activity</button></a> <br> <br>

<a href="/dashboard">Dashboard</a>
<br>
<a href="/announcements">Announcements</a>
<br>
<a href="/forum">Forum</a>
<br>
<a href="/assignments">Assignments</a>
<br>

{% endblock %}

widget_group3/calendar_app/templates/calendar_app/event-add.html
<!-- event add -->
{% extends 'base.html' %}
{% load static %}
{% block title %}Add Activity{% endblock %}

{% block content %}
{{ form.non_field_errors }}
{% for field in form %}
{% if field.errors %}
<p>{{ field.label }} has the following errors:</p>
<ul>
	{% for error in field.errors %}
	<li>{{ error }}</li>
	{% endfor %}
</ul>
{% endif %}
{% endfor %}
Add a new activity:
<form method="POST">
    {% csrf_token %}
	{{ form.as_p }}	
    <input type="submit" value="Save New Activity">
</form>
{% endblock %}

widget_group3/calendar_app/templates/calendar_app/event-details.html
<!-- event details -->
{% extends 'base.html' %}

{% block title %} {{object.activity}} {% endblock %}
{% block content %}
    <h1>{{ object.activity }}</h1>
    <h3>Date and Time: {{ object.target_datetime | date:"m/d/Y, h:i A" }}</h3>
	<h3>Estimated Hours: {{ object.estimated_hours }}</h3>
	<h3>{{ object.course.code }} {{ object.course.title }} - {{ object.course.section }}</h3>
	<h3>Mode: {{ object.location.mode }} </h3>
	<h3>Venue: {{ object.location.venue }}</h3>

<a href="{% url 'calendar_app:event-edit' object.id %}"><button>Edit Activity</button></a>

{% endblock %}

widget_group3/calendar_app/templates/calendar_app/event-edit.html
<!-- event-edit -->
{% extends 'base.html' %}
{% load static %}
{% block title %}Edit Activity{% endblock %}

{% block content %}
{{ form.non_field_errors }}
{% for field in form %}
{% if field.errors %}
<p>{{ field.label }} has the following errors:</p>
<ul>
	{% for error in field.errors %}
	<li>{{ error }}</li>
	{% endfor %}
</ul>
{% endif %}
{% endfor %}
Edit activity:
<form method="POST">
	{% csrf_token %}
    {{ form.as_p }}	
    <input type="submit" value="Save New Activity">
</form>
{% endblock %}